# Generated by Django 6.1.1 on 2026-09-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('highway', 'Highway'), ('railway', 'Railway'), ('irrigation', 'Irrigation'), ('industrial', 'Industrial Corridor'), ('urban', 'Urban Infrastructure')], max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('land_area_hectares', models.FloatField()),
                ('affected_families', models.PositiveIntegerField()),
                ('compensation_disbursed_pct', models.FloatField(default=0)),
                ('legal_disputes_count', models.PositiveIntegerField(default=0)),
                ('approval_delay_days', models.PositiveIntegerField(default=0)),
                ('possession_status_pct', models.FloatField(default=0)),
                ('rehabilitation_progress_pct', models.FloatField(default=0)),
                ('stakeholder_responsiveness_score', models.FloatField(default=5.0)),
                ('current_stage', models.CharField(choices=[('notification', 'Notification'), ('survey', 'Survey'), ('award', 'Award'), ('compensation', 'Compensation'), ('possession', 'Possession'), ('rehabilitation', 'Rehabilitation'), ('completed', 'Completed')], default='notification', max_length=20)),
                ('started_on', models.DateField()),
                ('target_completion', models.DateField()),
                ('is_delayed_historical', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
