# Generated by Django 6.0.8 on 2026-09-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalAcquisitionBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('area_acquired_ha', models.FloatField()),
                ('expenditure_cr', models.FloatField()),
                ('avg_cost_cr_per_ha', models.FloatField()),
                ('source', models.CharField(default='data.gov.in / MoRTH-NHAI', max_length=100)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
