# Generated by Django 6.0.8 on 2026-09-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_nationalacquisitionbenchmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landproject',
            name='current_stage',
            field=models.CharField(choices=[('notification', 'Notification'), ('survey', 'Survey'), ('declaration', 'Declaration'), ('award', 'Award'), ('compensation', 'Compensation'), ('possession', 'Possession'), ('rehabilitation', 'Rehabilitation'), ('completed', 'Completed')], default='notification', max_length=20),
        ),
        migrations.AlterField(
            model_name='landproject',
            name='started_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landproject',
            name='target_completion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
