# Generated by Django 6.1.1 on 2026-09-09 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('delay_probability', models.FloatField()),
                ('risk_band', models.CharField(max_length=10)),
                ('top_factors', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='projects.landproject')),
            ],
        ),
    ]
