# Generated by Django 6.0.8 on 2026-09-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
                ('training_sample_size', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
