# Generated by Django 6.0.8 on 2026-09-11 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_nationalacquisitionbenchmark'),
        ('risk_engine', '0003_actionitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='actionitem',
            old_name='description',
            new_name='ai_attribution',
        ),
        migrations.AddField(
            model_name='actionitem',
            name='action_ref',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='assigned_authority',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='evidence_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='execution_current',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='execution_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='model_influence_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='statutory_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('resolved', 'Resolved')], default='pending', max_length=12),
        ),
        migrations.CreateModel(
            name='RiskPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('risk_band', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_logs', to='projects.landproject')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
